### ISSUE TITLE
Angular override <head><title>

### ISSUE THREAD

**Issue by losh11** [litecoin-foundation/ltcspace#2]
We would like the title to be `Litecoin Space - page here` as defined in index.mempool.html, however some unknown process is overwriting this after the page is painted.

**Comment by alamshafil** [comment]
It looks `mempool` is being set in this file:
https://github.com/litecoin-foundation/ltcspace/blob/master/frontend/src/app/services/seo.service.ts

https://github.com/litecoin-foundation/ltcspace/blob/2f561d27f2728ac02125185c0aef2f0467beca4b/frontend/src/app/services/seo.service.ts#L8-L10

You could refactor the code in the file to only use "Litecoin Space" since the network name is added here:
https://github.com/litecoin-foundation/ltcspace/blob/2f561d27f2728ac02125185c0aef2f0467beca4b/frontend/src/app/services/seo.service.ts#L39-L43

**Comment by losh11** [comment]
Wow! Thanks for finding this.

**Comment by losh11** [comment]
Fixed w/ a78e559.

Once again, thank you for your help :)
